version: "3"
services:
  db:
    build: ./db
    platform: linux/x86_64
    container_name: db
    volumes:
      - ./db/data:/var/lib/mysql
      - ./sqls/init:/docker-entrypoint-initdb.d
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DB: todoList
      MYSQL_PORT: 3306
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: testUser

  todolist:
    platform: linux/x86_64
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DB: todoList
      MYSQL_PORT: 3306
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: testUser

volumes:
  mysql_data:
