on:
  push:
    branches:
      - main # mainブランチにプッシュされたときにデプロイが実行されます

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.GO_API_PEM_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.GO_API_PEM_KEY }}
          HOST: 172.31.15.188 # GitHub SecretsからEC2インスタンスのIPアドレスを取得
          USER: ec2-user # GitHub SecretsからEC2インスタンスのユーザー名を取得
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no -r . ec2-user@172.31.15.188:/go_rest_api
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@172.31.15.188 'cd /go_rest_api && sudo go run main.go'
