on:
  push:
    branches:
      - main # mainブランチにプッシュされたときにデプロイが実行されます
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.GO_API_PEM_KEY }}" > go_api.pem
          chmod 600 go_api.pem

      - name: Get PID
        id: get_pid
        run: |
<<<<<<< HEAD
          ssh -i go_api.pem -o StrictHostKeyChecking=no ec2-user@35.78.80.222 'sudo lsof -t -i:80 > pid.txt'
=======
          ssh -i go_api.pem -o StrictHostKeyChecking=no ec2-user@35.78.80.222 'sudo lsof -t -i:80' > pid.txt
>>>>>>> 2c9e9c17f096c9ed41750bb5e6792971ce3f0f04
          PID=$(awk '{print $2}' pid.txt)
          echo "PID=$PID"
          echo "::set-output name=pid::$PID"

      - name: Stop the application
        if: ${{ success() && steps.get_pid.outputs.pid != null }}
        run: |
          ssh -i go_api.pem -o StrictHostKeyChecking=no ec2-user@35.78.80.222 'cd ./go_rest_api && sudo kill ${{ steps.get_pid.outputs.pid }}'

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.GO_API_PEM_KEY }}
          HOST: 35.78.80.222 # GitHub SecretsからEC2インスタンスのIPアドレスを取得
          USER: ec2-user # GitHub SecretsからEC2インスタンスのユーザー名を取得
        run: |

          scp -i go_api.pem -o StrictHostKeyChecking=no -r ./* ec2-user@35.78.80.222:./go_rest_api
          ssh -i go_api.pem -o StrictHostKeyChecking=no ec2-user@35.78.80.222 'cd ./go_rest_api && sudo go run main.go'
